aliBuild
Needed when updating a bare repo.
=> Specify remote URL when fetching in reference repo

aliBuild
This will emit a debug message specifing what it considers as the main package
being built, including the sources used and their hash.
This will be used to better categorize builds and show together builds which
belong to the same commit.
=> Emit an event for the main package.

aliBuild
When using debug output, we now print out the "main package" and the hash used
for it. This will allow us to aggregate different builds of the same main
package, e.g. when building for different architectures or with different
version of some external (e.g., geant 4). This should simplify comparisons
and parsing with logstash.
=> Improve logging to associate it with a given build.

aliBuild
This uses the tarball symlinks, rather than the actual installation directory,
to derive the installation revision. This is done so that we can actually sync
the symlinks from server and ensure we have a consistent setup, not only for
the hash based storage, but also for the tarball friendly names.
=> Use tarball symlinks to determine revision.

aliBuild, build_template.sh
With this aliBuild creates a directory per package in the store, where all the
dependencies of a given package are to be found. Convenience apart, this opens
many possibilities, including the ability to garbage collect builds and to
provide repositories for (say) yum or apt-get, in a separate way.
=> Create a fully bound distribution of every package built.

aliBuild
When in development mode, detect uncommitted changes and include
them in the hash of the package being built.
=> Detect uncommitted changes in source.

README.md, aliBuild, build_template.sh
When developing locally using the `--devel` mode, if the external is well
behaved and supports incremental building, it is possible to specify an
`incremental_recipe` in the YAML preamble. Such a recipe will be used after the
second time the build happens (to ensure that the non incremental parts of the
build are done) and will be executed directly in $BUILDDIR, only recompiled
what changed. Notice that if this is the case the incremental recipe will
always be executed.
=> Add support for incremental builds.

aliBuild
There is a corner case when two packages have an overlapping version
which includes a -, say alice3 and alice3-xrd. If the latter was already
uploaded, the former will still think its revision is a possible
candidate, but will then fail to match later on, which is correct.
However if there is no other tarball available, we will end up crashing,
rather than simply assigning "1" as a revision.
This handles the problem by simply detecting the fact there is no
revision candidates and therefore picking 1.
=> Handle corner case with overlapping versions. Fix alisw/alidist#72.

aliBuild
Previous mechanism was failing in case a main package was depending on another
like it's the case now for O2.
=> Correctly detect the main package.

build_template.sh
The `@@@PKGREVISION@<hash>@@` relocation, while correct, was replacing a file
which was already relocated with an old version. Fixed by doing both changes at
the same time.
=> Fix PKGREVISION relocation undoing the actual path relocation.

aliBuild
Previous algorithm was not taking into account more than 1 level of dependencies. This should fix #60.
=> Sort dependencies using a proper topological sort.

aliBuild
Devel packages install directly into the prefix, so we cannot properly
create cached tarballs, this avoids them.
=> Do not use cached tarball for devel packages

README.md, aliBuild
In the future build_requires will only be used if a package needs to be built.
For now we simply use it to distinguish between different kind of requires and
produce prettier dependencies plots.
=> Introduce the concept of build_requires

README.md, aliBuild
Useful in case you are using tags like:
alice/v5-34-18
for ROOT but you want it to be called:
v5-34-18
=> Add tag_basename expansion for version value

aliBuild
When a remote store is specified, we also populate the toplevel
directory "dist-runtime" which contains only the packages which are
required at runtime. This is done so that we can avoid publishing things
like autotools and cmake on Alien.
=> Publish requires which are runtime only

aliBuild
Previous implementation was always showing the value for the master
branch.
=> Show the correct git hash for alibuild / alidist

README.md, alfaBuild
This is useful for cross platform builds. No more having to spawn the
containers on your own. For the moment only slc7 is used, but it's easy
to allow any kind of container.
=> Allow build to happen inside a docker container

build_template.sh
Bash caches executables in $PATH for faster retrieval: we disable it to prevent
intermittent problems when we need to use a just-built package that, for
instance, overrides a system tool already in the cache. The latter could get
invoked instead with caching on (which is the default in Bash).
=> Disable shell path caching

aliBuild
This is to avoid that common dependencies, like GCC, blow up
the environment.
=> Avoid multiple source of dependencies

README.md, aliBuild
Rather than having to opt in for devel packages, the user has now to opt
out. This simplifies local development of external packages and makes it
as easy as doing multiple checkouts in the same directory. This behaviour 
can be selectively disabled for using the new option `--no-local`.
=> Enable development packages by default.

aliBuild
To prevent confusion if both are accidentally used together.
=> Do (not) use system tools opts mutually exclusive

aliBuild
Docker cannot run "osx" containers. This does not mean you cannot run
`--docker -a slc7_x86-64` or alikes on Mac.
=> Complain if --docker is used with -a osx.*

aliBuild
=> Drop hostname from riemann report

aliBuild
Cleanup build byproducts after the build. In particular it removes
INSTALLROOT/<package-hash> and BUILD/<package-hash> which are not really
needed in case of a successful build.
Notice this only happens in case a package is not a development package
since in that case build byproducts will be reused in a subsequent
build.
=> Cleanup unneeded build by products

aliBuild
Also works on old Macs. Defaults to 1.
=> Autodetect number of CPUs

README.md, aliModules
More intuitive usage with sensible defaults: it works out of the box with zero
parameters.
Also detects modulecmd on various platforms, including Homebrew installations on
OSX. A platform-specific installation hint is printed if modulecmd is missing.
=> Improve aliModules and simplify its usage

alienv
alienv takes the same basic commands as the CVMFS version. This is aimed to
provide a more uniform user experience.
=> Manage modules in a way compatible with CVMFS

build_template.sh
Same rationale as #153 but:
- works if recipe does not provide a modulefile
- works with all sed flavors (i.e. on Ubuntu, `-i` with extension is not
supported)
=> Correctly relocate modulefile in devel mode

aliBuild
Rationale: if running `aliBuild -w yabbayabba -d build YabbaYabba` I expected the reference sources to be under `yabbayabba/MIRROR` but they were not stored anywhere - it attempted to store them under `sw/MIRROR`, but `sw` did not exist and it gave up. This PR defaults reference sources as the `MIRROR` subdirectory of the current working directory whatever it is called.
=> Store references by default as a subdir of workdir

alienv, alienv.bashrc, alienv.kshrc, alienv.zshrc
Environment to source in your `.<whatever>rc` shell script to use `alienv` with a shortcut. Automatically load environment in _current_ shell when doing `alienv [load|unload]` without specifying `eval` manually.
=> alienv shortcut

aliBuild
This allows to gracefully handle builds of multiple branches in development packages. Each branch will get it's own installation area, named after the branch, so that one can actually compare results.
=> Handle multiple branches in development builds

aliBuild
Use `git-rev-parse` without `--abbrev-ref` if we are on a dangling
commit.
=> Handle detached checkout for devel packages.

aliBuild, build_template.sh
In order to differentiate between the various builds, we add an extra
symlink which keeps the develPrefix into account. This way you can find
the latest build on branch master via:
<prefix>/<architecture>/<package>/latest-master
=> Add symlinks to latest-<develPrefix>

aliBuild
Most likely mixing our and anaconda python packages will not work,
but at least it should proceed when compiling.
=> Detect Ubuntu running anaconda

aliBuild
Add ability to specify packages which can only be picked up from
the system. This is different from prefer_system as the package is
mandatory.
=> Introduce system_requirement

Jenkinsfile
Whenever a new test is required, send a Slack message pointing to the
progress page (eventually asking for approval).
=> Add slack notification for alibuild-pipeline

aliBuild
This should provide better support for Ubuntu like distributions
(like LinuxMint). This also better fixes the ANACONDA issue.
=> Use /etc/os-release for architecture detection

setup.py
The `release-alibuild` pipeline in Jenkins will replace this placeholder
with the correct version obtained from the current tag of the master
branch.
=> Change default version to LAST_TAG

setup.py
- Add argsparse as a dependency (so that it works out of the box on
certain python 2.6 installations.
- Distribute shell helpers.
=> Improve packaging

alienv
Currently there is a switch, `--clean-env|-e`, to start a new shell by ignoring whatever startup file the shell uses (_i.e._ `.bashrc`). The default should be the same as on the Grid, _i.e._ your settings are always ignored.
=> Make alienv enter ignore .bashrc by default

alienv
`alienv q` displayed package/version instead of VO_ALICE@package::version due to
a non-cross-compatible `sed` syntax.
=> Fix alienv q display on OSX

.travis.yml, aliBuild
This prevents using the `write_repo` when pulling, if for some reason user has no access to it.
=> Add push URL instead of changing pull too in init

Jenkinsfile, aliBuild, alibuild_helpers/__init__.py, alibuild_helpers/utilities.py, tests/test_utilities.py
Now the helper for architecture detection is pure and has its own
unittest. This should make sure we do not inadvertly change the
architecture while trying to support a different one.
=> Improve architecture detection

aliBuild
Fixes #212.
With this fix when using a `develPrefix` this is used to compute the hash to determine the build directory. This means that the same package, in development mode in two different prefixes, has two distinct build (and install) dirs.
=> Make build dir for devel packages depend on prefix

aliBuild
* Tells user about possible outdated sources when they fail to build
* Warn at the beginning about possible outdated branch by showing `git status` for every development package
Fixes #246.
=> Print update tip for development packages

aliBuild
* Log messages have colored and underlined level
* Add `banner()` for emphatic INFO messages (behaves like `info()` if no tty), inspired by Homebrew
* Build process in non-debug mode shows a moving splash bar
Colors and splash progress are turned off if no tty is available (e.g. if run from a script or
Jenkins).
Fixes #256.
=> Implement colored logging and splash bar on ttys

alienv
On my system where the command in the ps results is "-zsh" the \? of
the regular expression used to get the shell name do not seem to work fine...
=> Regexp special character \? not working on all systems. Replaced with \{0,1\}

aliBuild
* Multiple build directories
* Multiple installation directories
This aims to fix #212.
**NOTE:** not for merging, this is a proposal to be discussed as it might have some impact, and better solutions might exist.
What it does: overrides whatever `version:` was specified in the recipe _if and only if_ the following two conditions are met:
1. The package is in development mode
2. A development prefix was specified
=> Fix for multiple devel branches for the same pkg

aliDoctor
This should obviate the issue with prefer_system_check using brew (on
Mac) to looks for system packages. On linux this fails because brew is
not there creating confusion, while being harmless.
This fixes the problem by replacing "brew" with "true" in case brew is
not found in path.
Fixes alisw/alidist#296.
=> Avoid spurios messages in aliDoctor

aliBuild
Development packages used a random `commit_hash`, which came from a remote head (`git ls-remote`) and not necessarily for the currently checked out branch. This was not a problem until #282 where we use this piece of information to determine whether it is necessary to rebuild a development package.
If we get this information from the remote only, it might happen that package rebuild is not triggered in case we don't have local modifications, and in case we are moving back and forth pushed commits via `git reset --hard`.
=> Use commit_hash from local src for devel packages

aliBuild
$WORK_DIR/TMP is simply a temporary place where we unpack things
before atomically moving them in place. It should always be empty
at the end of a job unless unpacking fails so it's safe to always
delete it when we invoke aliBuild clean.
=> Clean $WORK_DIR/TMP on aliBuild clean

aliBuild
- Now supports the --aggressive-cleanup option, which can be used
to remove extra files which come handy only in case of rebuilds.
This means that in general the cleanup has no side effects, but
it will take longer to rebuild a package.
- Do not remove files which do not exists.
=> Improve aliBuild clean

aliBuild
aliBuild was not protecting against previously setup environment under
some circunstances. This should make sure the build environment will
always override the one previously set.
Notice there might still be leaks of the user environment into the build
one, but to have a definitive solution for this we would need to move to
rely on modulefiles only.
=> Protect again aliBuild in alienv cornercase

alienv
In case of shared installations users using `alienv` do not normally have
permissions to regenerate the modulefiles directory. `alienv` now detects this
case and does not attempt to regenerate it. This saves users from adding
`--no-refresh` manually.
=> Default alienv to --no-refresh on read-only fs

alibuild_helpers/utilities.py, tests/test_utilities.py
`platform.processor()` can be very verbose, prefer `platform.machine()`
if that is actually the case.
=> Improve CPU type detection

aliBuild
This should allow us to incorporate what is currently a different
branch to a set of overrides which can be specified in the defaults
file. The idea is that an `o2` default could for example disable
AliEn and switch to ROOT6.
=> Allow defaults to disable packages and overrides

aliBuild, alibuild_helpers/utilities.py
This makes sure that system checks are done inside docker rather than
on the host. This should fix #339.
=> Fix system_requirements and docker

aliBuild
This adds the ability to specify a docker image when building using
docker. If the option is not present, it will fall back to the usual,
architecture derived, one e.g. alisw/slc7-builder.
=> Add --docker-image option

alibuild_helpers/analytics.py
Python 2 and python 3 have different behaviors when it comes to
raw_input and input builtins. The previous approach was not working
correctly, while this seems to be ok.
=> Fix raw_input / input discrepancy

aliBuild
Single recipes can be overridden (_e.g._ to provide a hotfix) in defaults using
overrides by specifying the package name followed by the Git reference (hash,
tag...) where the recipe should be picked from. Overrides are temporary and do
not alter the current checked out recipes directory.
=> Add recipes override from the defaults

aliBuild, alibuild_helpers/build_template.sh
This introduces the concept of build family. Basically until now
only the development packages were getting a latest-<devel-prefix>
link, while any of their descendents did not. This leads to issue
when cleaning up as described in:
<https://github.com/alisw/alibuild/issues/325>
With this change we introduce a new concept, the build family, which is
common to all packages which are involved in the build of a development
package or which use a particular default. It allows us to create a
latest-<build-family> link for each package involved in the build.
<build-family> will be either:
- `<devel-prefix>-<defaults>`
- `<defaults>`
depending on whether the package is a devel package or not.
=> Introduce the concept of build family

aliBuild
If aliBuild dies while creating the temporary archive, e.g. due to
a disk full, subsequent runs die trying to expand the half finished
tarball. While we have a protection which should move the tarball in
place atomically, the mechanism looking up for cached tarballs could
still pick up the .processing one. This makes sure all the tarball we
get actually end in `gz`, hence fixing the problem.
=> Self-heal setup after a full disk

.travis.yml, aliBuild, aliDoctor, alibuild_helpers/utilities.py, tests/test_parseRecipe.py
By using the same set of functions, aliBuild and aliDoctor should now
behave exactly the same. It's also now possible to pass --disable and
--defaults to aliDoctor and get the diagnosis for the chosen setup. By
factoring out the IO related code, this should also improve our ability
to unit test things.
=> Unify defaults / disable support in aliBuild / aliDoctor

docs/o2-tutorial.markdown
Since this comes extremely hand, with Barth we decided to have it in the
instructions even if the supporting aliBuild is stil unreleased.
=> Update doc for the new o2 defaults

aliBuild
Given a package aliBuild did not delete a given version, e.g. v1.0, if a
symlink called latest* existed in any package, not only in the one being
looked at. This caused a few packages not being deleted.
This resolves the issue by making sure that the `latest` link is
actually in the same directory.
=> Fix aliBuild clean

aliBuild
This is to avoid sourcing misbehaving bashrc files.
=> Unset BASH_ENV

aliBuild
Previously write store was disabled in case a development package was
found in the dependency tree. This changes the behavior to be less
aggressive and disables the ability to write to the store only once the
first development package is encountered while building.
=> Disable write store only at first devel package

.travis.yml, aliBuild, alibuild_helpers/utilities.py, tests/test_parseRecipe.py
Some packages can only be compiled using a given default. Most notably,
the O2 package can only be built with `--defaults o2` or `--defaults
o2-daq`. It's now possible to express that by adding a valid_defaults
entry in the YAML preable which contains the list of valid defaults.
=> Introduce valid_defaults metadata

alibuild_helpers/log.py
Building O2 with aliBuild I get an exception in aliBuild. The problem is the unicode character 2026, the horizontal ellipsis, i.e. three dots as one character. Following https://docs.python.org/2/howto/unicode.html I replace all non-ascii characters in the logger.
```
== old == 
DEBUG:O2:O2-master: -- Looking for ZeroMQ...
DEBUG:O2:O2-master: -- Looking for ZeroMQ... - found /home/hbeck/alice/alibuild/sw/ubuntu1604_x86-64/ZeroMQ/v4.1.5-1/lib/libzmq.a;/home/hbeck/alice/alibuild/sw/ubuntu1604_x86-64/ZeroMQ/v4.1.5-1/lib/libzmq.so 4.1.5
Traceback (most recent call last):
File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
msg = self.format(record)
File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
return fmt.format(record)
File …
```
=> Replace non-ascii in logger

aliBuild
The old message suggested the user to use `alienv enter` with a non-existing package.
=> Add defaults name to message when build ends

alibuild_helpers/build_template.sh
Turned out to be a very bad idea when doing integration builds.
=> Do not append log when doing an incremental build

alibuild_helpers/build.py, tests/test_build.py
Some idea to speed up the start of the build phase. I have only tested it on python 2.7.13 (macOS 10.11), but it should work from 2.4+ on or so. It saves in the order of 15 seconds for me on larger dependency trees like `O2` or `FairRoot`.
=> prefetch git heads in parallel

alibuild_helpers/log.py, tests/test_log.py
When not in debug mode, the "X is being built" message also shows the percentage
of completion if detected in the underlying command output. This is expecially
useful when running builds for CMake-based projects.
=> Show progress percentage while building

alibuild_helpers/build.py, tests/test_build.py
In case /bin/bash is present we keep honouring using it for backward
compatibility. In case it's not, we fall back to whatever bash is in
path.
=> Allow non /bin/bash file location for bash

alibuild_helpers/build.py, tests/test_build.py
If pip needs to be updated, using it will print a spurions
message whenever it's being used. This avoids such a message.
=> Fix spurious message in alibuild version

alibuild_helpers/build_template.sh
Hi,
This commit fixes the leak of dylib relocations.
Previously fastjet build was failed with SIP due to the cgal dylibs are not correctly relocated.
Some dylibs which install_name only contain basename (no / in its name!) part are fixed to have abs path.
After this change, fastjet should build successfully.
=> Fix dylib relocation and support System Integrity Protection

alibuild_helpers/build.py, alibuild_helpers/cmd.py, alibuild_helpers/doctor.py, alibuild_helpers/utilities.py, tests/test_cmd.py
(Also move Bash detection to cmd module and cache result.)
This fixes a serious problem when checking system packages: we assume the syntax is Bash's (therefore we are not POSIX-compliant), but we cannot rely on Python's shell choice. By default it's `/bin/sh`, which on _some_ Ubuntu systems is `/bin/bash` (OK), but on a large number it's `/bin/dash` (POSIX: not OK for us).
We need to make sure checks are executed in Bash.
Code for automatic detection of Bash (`/bin/bash`, `bash`) has been reused.
=> Force use of /bin/bash when checking system deps

aliBuild, alibuild_helpers/args.py, alibuild_helpers/build.py, alibuild_helpers/init.py, docs/user.markdown, tests/test_args.py, tests/test_build.py, tests/test_init.py
This patch is quite useful when having only a slow or unreliable
Internet connection available, e.g. in trains or planes.
This patch changes the default behaviour of the `{build,init}` subcommands, so that they only clone the reference repos, if they are missing. The user has to pass `--fetch-repos` or `-u` to force fetching updates to the reference repos.
This patch reorganizes the `updateReferenceRepos` calls to before the build loop
and extracts the git heads from the local repos only. ~~If `--offline` flag
is passed the `updateReferenceRepos` calls are skipped.~~
---
Hope, we can take this as a start to resolve #323. What do you think? Still needs testing, just hacked this together half an hour ago ;) But it was really annoying to wait 20 seconds in the train for fetching the git …
=> Only clone reference repos by default, fetch updates with --fetch-repos or -u

alibuild_helpers/build_template.sh
Technically, this fix does not just change the relocation for the case
of CMake files. But, excluding the semi-colon from the set of characters
expected to be used in directory names seems fairly generic though. We
already exclude spaces, which are far more likely to be used in
directory names.
Fixes #508
=> Fix relocation for CMake files

alibuild_helpers/build.py, alibuild_helpers/workarea.py
If a mirror is read-only, ignore it and move on, otherwise fetch
the heads.
=> Allow read-only references

alibuild_helpers/workarea.py
`git fetch` does not fetch all upstream branches by default, just the HEAD
=> Ensure we fetch ALL heads when updating reference

alibuild_helpers/workarea.py
See the `refspec` description on `man git-push`. Initial `+` is required to allow for local references to be force-updated (non-fast-forward)
=> Allow force-updating from remote references

alienv
* Detect parent shell only when needed
* Update modulefiles only when needed
This solves a problem having all new shells using the `shell-helper` hanging
for ~2s because alienv was wasting time in unneeded operations.
=> Improve alienv performance

alibuild_helpers/build_template.sh
When using `set +h`, the `hash` command returns nonzero with a warning saying
that hashing is disabled. To prevent recipes using `hash` to fail without
changing them, the `hash` command is being aliased to a no-op.
Note that this was introduced in #503 since:
* hashing is disabled in the `build_template.sh` shell environment,
* the recipe turned from being executed in a separate shell to being sourced in
the current shell (thus retaining the `set +h` option).
=> Disable shell hash command as hashing is disabled

alibuild_helpers/build.py, tests/test_args.py, tests/test_build.py
If environment variables were specified in the command line via `-e` arguments, the build script would try to split the value on `=`, but erroneously passed the string `'1'` (not the integer `1`) into `str.split`.
This fix uses `str.partition` to split on 0 or 1 instances of '=' (the zero case will store the empty string into the environment variable)
=> build: Fix handling of command-line environment variables

setup.py
Since 3.2 it's actually part of the python upstream distribution.
=> Make argparse optional install_requires

alibuild_helpers/deps.py, tests/test_deps.py
Python 3 writes bytes, not strings. Writing pure text allows us to pass strings
to `write()` as well.
Fixes #556.
=> Set aliDeps temp file mode to text

alibuild_helpers/build_template.sh
Because otool is extremely slow, it really speeds up things to
make sure we check with it ambiguous files, not things we know
in advance are not libraries.
=> Improve speed of macOS binaries relocation

alibuild_helpers/workarea.py, tests/test_build.py, tests/test_workarea.py
The idea is that if someone moves a tag upstream, we should
still be able to fetch the new one and rebuild. This should be
transparently handled by aliBuild in any case, since alibuild
resolves the commit hash to create the packaging hash.
=> Force fetch mirrored tags / branches

alibuild_helpers/build.py, alibuild_helpers/build_template.sh, alibuild_helpers/utilities.py, docs/reference.markdown
DYLD_LIBRARY_PATH does not work anymore in subshells if SIP is enabled.
Since we have long switched to @rpath on mac, we can finally drop
these so that we also avoid issues with conflicting library versions.
=> Drop DYLD_LIBRARY_PATH usage

docs/reference.markdown
Here are several documentation points to be developed about aliBuild.
The idea would be to have an ~advanced documentation to be used as reference.
Proposed items (@qgp, @marcovanleeuwen) : 
- advanced concepts of aliBuild (e.g. relocation step is little known) and recipes incl. conventions (e.g. variables to export in module file)
- known limitations/issues (e.g. fastjet-config until recently), to simply know what is not expected to work (and possibly decide to fix it)
- basic strategy for comment to be enforced into recipes
(CC to @preghenella)
=> aliBuild/docs - reference section, TOC

alibuild_helpers/build_template.sh
This speeds up recompilation of large packages like GEANT4, Python-modules.
=> Allow using pigz in a few more places

.travis.yml, alibuild_helpers/build.py, alibuild_helpers/build_template.sh, alibuild_helpers/git.py, alibuild_helpers/init.py, alibuild_helpers/workarea.py, tests/test_build.py, tests/test_init.py
Now that Github support partial clones, we can probably greatly
reduce the amount of space taken by source checkouts by adding
the --filter=blob:none option to git clone.
Such an option will make sure that only the blobs which are
of interest for the current checkout are downloaded.
Full docs at https://git-scm.com/docs/partial-clone
The only caveat will be to detect when the client (most notably CC7)
supports it (C8, macOS and Ubuntu are all fine).
=> WIP: Use --filter=blob:none

alibuild_helpers/args.py, alibuild_helpers/build.py
This is required so revision numbers don't conflict.
Adds a mode to `getRetry` to return the contents of a remote file, to make symlink creation easier.
=> HTTP backend: create dangling symlinks

alibuild_helpers/build.py, alibuild_helpers/deps.py, alibuild_helpers/doctor.py, alibuild_helpers/init.py, alibuild_helpers/utilities.py, docs/reference.markdown, tests/test_init.py
This works in parallel of the usual "defaults" mechanism to override recipes on
a per architecture basis. For example to disable a given common package like
autotools or to force some compiler options which are specific for a given
architecture.
=> If available, have architecture specific overrides

alibuild_helpers/build.py
We want the symlinks created without the newline.
I've tested this in an SLC8 container, which has stray symlinks without this PR, and none with this PR.
=> Strip trailing newlines from fake-symlink entries on S3

alibuild_helpers/build.py
This prefix was removed in `syncToRemote`, but not re-added in `syncToLocal`.
=> Add ../../ back to symlinks from S3

alibuild_helpers/build.py
This prefix is removed in `S3RemoteStore.syncToRemote`, but needs to be restored here too, as the HTTPS remote is used to access S3 as well.
@ktf, I assume the HTTPS remote is *only* used to access S3. Is that right? If not, this might need to be handled specially.
=> Also restore leading ../../ for HTTPS remote

alibuild_helpers/build.py
aliBuild fails with the following traceback on Ubuntu 18.04:
Using cached build for golang
Traceback (most recent call last):
File "/usr/local/bin/aliBuild", line 132, in <module>
doMain(args, parser)
File "/usr/local/bin/aliBuild", line 82, in doMain
printer, msg, code = doBuild(args, parser)
File "/usr/local/lib/python2.7/dist-packages/alibuild_helpers/build.py", line 862, in doBuild
shutil.rmtree(dirname(hashFile), True)
File "/usr/lib/python2.7/shutil.py", line 270, in rmtree
rmtree(fullname, ignore_errors, onerror)
File "/usr/lib/python2.7/shutil.py", line 270, in rmtree
rmtree(fullname, ignore_errors, onerror)
File "/usr/lib/python2.7/shutil.py", line 270, in rmtree
rmtree(fullname, ignore_errors, onerror)
File "/usr/lib/python2.7/shutil.py", line 264, in rmtree
fullname = …
=> Fix directory removal on Python 2

alibuild_helpers/build.py, alibuild_helpers/deps.py, alibuild_helpers/doctor.py, alibuild_helpers/init.py, alibuild_helpers/log.py, alibuild_helpers/utilities.py, alibuild_helpers/workarea.py, tests/test_build.py, tests/test_doctor.py, tests/test_init.py, tests/test_log.py, tests/test_parseRecipe.py
Logging functions (like `debug`, `info`, `error`) can take extra arguments, which are substituted into the message using printf-like syntax (`%s` and the like). This formatting is only done if the given logging level is actually enabled, giving some minor speed up in case debug logging is disabled. It also makes the code cleaner, as e.g. `debug(format("%s %s", a, b))` can be written as `debug("%s %s", a, b)` instead.
This patch also updates unit tests to work with the built-in logging convention.
Also includes fixes for the minor problem where `err = execute(cmd); debug(err, cmd)` would not output `cmd`; only `err` (the exit code) without explanation. I've changed this to output both `cmd` and `err` with a more descriptive message.
Tested and working.
=> Use args of logging functions for lazy formatting

alibuild_helpers/build.py, alibuild_helpers/cmd.py, tests/test_build.py, tests/test_cmd.py
This prevents interference between the remote store and local builds in the case where another machine builds a package and uploads it to the remote store with a revision number that conflicts with a local package, in case that package wasn't uploaded to the remote store. In that case, local revision numbers become a mess, and packages could start depending on the wrong revision numbers of dependencies.
It also prevents builds intended only for local use from being uploaded to the remote. This is important as local-only builds might otherwise be uploaded to the remote much later, when some of their dependencies might conflict with new ones on the remote, and would be renamed. In that case, we currently don't update the main package, so it would depend on (and e.g. try to source scripts …
=> Separate local-only builds from remote revisions

alibuild_helpers/build.py, tests/test_build.py
Local revisions get a different hash (with the same information as remote revisions, but an extra "local" string in the input to the hash). This is to avoid conflicts where a remote might gain a package with the same hash as a locally-built package; in that case, the two would conflict. With this patch, the two revisions of the same package should be able to coexist.
Syncing from and to remote stores can always use the remote-specific hashes. Once we have assigned a revision to the package (or reused an existing one), we know which hash (remote or local) to assign and use for the build.
This commit also extracts the hash calculation into a separate function for cleanliness.
The same hashes are still generated for the same specs, so existing tarballs on the remote store are used.
A bit of …
=> Calculate separate hashes for local and remote revisions

alibuild_helpers/build_template.sh
This fetches the tags of existing git repos if desired tag can't be checked out, then retries checking out the desired tag. This only results in an extra network request per repo (which might mean an extra password prompt) if the tag doesn't already exist, which happens if the tag was made after the repo in `SOURCES` was first cloned.
This doesn't catch cases where a tag moves, or where `$GIT_TAG` is a branch, not a
tag.
=> Update existing git repos if we can't checkout the tag

alibuild_helpers/build.py
We shouldn't be producing conflicting symlinks anyway, and if we do, it's probably better if we just keep our local one.
This should reduce the remote sync time significantly on subsequent runs of aliBuild (though we'll still have to download everything on the first run).
On slc7, when we don't have to rebuild anything, this change takes the runtime of `aliBuild build O2 --defaults o2` from 5 minutes to 16 seconds.
=> Don't redownload existing symlinks

alibuild_helpers/init.py, tests/test_init.py
=> Revert "Use standard name for upstream remotes."

alibuild_helpers/sync.py
Previously, trailing slashes would be stripped from paths. This led to unintended symlinks being created under `TARS`, e.g. when trying to fetch `TARS/slc7_x86-64/O2/`, `TARS/slc7_x86-64/O2` would be used as the prefix instead, leading to O2Suite symlinks being included in the result as well.
We do want to strip leading slashes from the prefix, so use `str.lstrip` instead.
=> Fix directory listing using S3 HTTPS API

alibuild_helpers/build.py
This makes the situation where requirements are default-dependent less confusing.
=> When suggesting aliDoctor command, pass through --defaults

alibuild_helpers/args.py, alibuild_helpers/utilities.py, tests/test_args.py, tests/test_clean.py, tests/test_cmd.py, tests/test_init.py, tests/test_log.py, tests/test_workarea.py
- add a `--force-unknown-architecture` to each command that needs it for tests
- update distro versions in the help message that is shown when an unknown architecture is detected
- add recent Debian versions to the Debian -> Ubuntu conversion table
- fix warnings thrown from `alibuild_helpers.utilities.doDetectArch` due to unclosed files when running `uname -m`
- handle the case where `platform.processor() == ""` but `platform.machine()` is fine -- in that case, we don't need to call `uname -m`
- clean up `args` tests a little, testing invalid architectures as well
- clean up tests' imports, so we don't need `mock` installed when using python3
@ktf, with this PR, I can actually run alibuild's tests on my machine instead of making a docker container each time. I cleaned up a few things on …
=> Allow running tests on unknown architectures

alibuild_helpers/init.py, tests/test_init.py
This reverts commit 22c610abad8092b304b88b01fdbe0d162794278d.
Related PRs:
* https://github.com/alisw/alisw.github.io/pull/97
* https://github.com/alice-doc/alice-analysis-tutorial/pull/128
=> Revert "Revert "Use standard name for upstream remotes." (#673)"

alibuild_helpers/utilities.py
On slc6, `distribution` is `CentOS` initially, so we need to make it lowercase to match.
=> Autodetect slc6 correctly

alibuild_helpers/init.py, alibuild_helpers/utilities.py
It is passed a function that takes one argument -- normally `argparse.ArgumentParser.error` -- instead of `alibuild_helpers.log.error`. Also patch the one place where this isn't true, in `init.py`.
=> Fix use of logging function in readDefaults

alibuild_helpers/args.py
We build O2 nightly, as for slc7.
Tested in a fresh `alisw/ubuntu2004-builder` container, with aliBuild installed using `pip3`.
=> Use remote store by default on Ubuntu 20.04

alibuild_helpers/build.py, alibuild_helpers/utilities.py, tests/test_utilities.py
If the image has an entrypoint, it will be prepended to our command. We don't want that, so explicitly override it to the empty string.
Tested and working in the fullCI checkers.
=> Override Docker image entrypoint

alibuild_helpers/sync.py
For downloads, debug output is already shown.
This should make it easier to debug problems with S3 uploads.
=> Show s3cmd debug output for uploads as well

.github/workflows/release.yml, aliBuild, alibuild_helpers/__init__.py, alibuild_helpers/utilities.py, script/cibuild, setup.py, tests/test_utilities.py
Currently, recent Python 3 versions will throw a `ResourceWarning` from `pkg_resources` when getting the installed version number in unit tests. This patch fixes that.
Storing the version number internally also means we don't need a fallback in case alibuild isn't installed with pip.
The version number is still only stored once. `setup.py` simply gets it from the same place as the `aliBuild` script.
=> Store version in alibuild_helpers instead of setup.py

alibuild_helpers/build.py, alibuild_helpers/sync.py, alibuild_helpers/utilities.py, requirements.txt, setup.py, tests/test_build.py, tests/test_sync.py
Add a new class that fetches tarballs from S3 using boto3. Compared to the existing S3RemoteSync, this doesn't require s3cmd to be installed separately. The new remote also doesn't overwrite existing tarballs and links in S3 (which S3RemoteSync does).
Boto3 only supports Python 3.6+, so the new remote store can only be used under those Python versions.
I've tested fetching (read-only) and uploading (read-write) using the boto3 remote (both work for me).
I've also added new unit tests to cover the boto3 remote (and also extended the previous test to cover the old S3RemoteSync).
=> Add boto3 remote store

alibuild_helpers/init.py, tests/test_init.py
Using:
```
--filter blob:none --origin upstream
```
does not work on Ubuntu 18.04 (16% of our users). Given in any case if you do aliBuild init most likely you want a complete repository, I guess it's ok to disable the partial clone for now.
=> Do not use --filter blob:none for aliBuild init

.gitignore, alibuild_helpers/build.py, alibuild_helpers/sync.py, alibuild_helpers/utilities.py, docs/user.markdown, tests/test_build.py, tests/test_hashing.py, tests/test_sync.py
Store alternative hashes for a spec, for each other git reference we could've used to point to the commit we're actually building. This means that we can e.g. reuse tarballs built from commit `abcde` when building tag `foo`, if `foo` tags the commit `abcde`.
This currently works both ways -- if we're building a commit, look for tags pointing to it, and if we're building a tag, look for the commit hash and other tags pointing to the same commit. This makes the assumption that tags don't move around!
Tested using python3 on slc7 and slc8 for each remote store (rsync, S3, boto3, HTTP).
=> Consider all possible hashes when building tag

alibuild_helpers/sync.py
This fixes a mistake where aliBuild would upload dist links with their full path as the key, which also breaks RPM publishing.
=> Fix upload of dist links using s3:// remote

alibuild_helpers/build.py, tests/test_build.py
If we have both a local and a remote tarball that both match the hashes we want, reuse the remote tarball instead of the first one we find. This allows us to potentially reuse remote (or local) tarballs for later packages. If we find multiple reusable tarballs, prefer the one with the "primary" hash.
Draft until I test it properly.
=> Prefer remote revisions to existing local revisions

alibuild_helpers/build_template.sh
Cloning or checking out the associated git repo is unnecessary if we're just reusing a prebuilt tarball. Skipping this step can save significant build time, especially for large packages like GCC or Clang.
To be tested.
PR 1/n replacing #683.
=> Don't clone git repo if we're using a prebuilt tarball

aliBuild, alibuild_helpers/build.py, tests/test_build.py
Previously, `doBuild` returned a logging function, a message and an exit code. We only really need the exit code, and might as well do the logging in `doBuild` itself.
The unit tests can still check for the correct final logging message with a mock logging function.
=> Make doBuild's return type more sane

alibuild_helpers/build.py, tests/test_build.py
The version is only shown once, before starting the build. Instead of calling pip (and getting error messages more often than not), use the version number stored in `alibuild_helpers.__version__` instead. This brings it in line with what `aliBuild version` displays.
=> Get alibuild version directly, instead of calling pip

alibuild_helpers/sync.py
Sometimes, this isn't created beforehand, causing errors when syncing symlinks from an `rsync://` remote store.
=> Create links directory for rsync remote

alibuild_helpers/build_template.sh
Some libraries built on OSX can have LC_RPATH entries for multiple architectures. In that case, they'll have the same rpath multiple times, but a single `install_name_tool` call will change all of them, and subsequent calls will fail.
Instead, only consider each unique rpath only once.
=> Fix relocation of libs with multiple LC_RPATH entries

alibuild_helpers/args.py, alibuild_helpers/doctor.py, docs/user.markdown, tests/test_args.py
Lots of command-line options had no documentation at all when running `aliBuild <command> --help`. This PR fixes that and makes the existing help text more consistent across commands.
I changed a few small parts of argument parsing:
- I removed the ability to specify a `%(prefix)s` in `--config-dir` for `aliBuild build` -- it was always substituted with the empty string.
- `aliBuild init` still has this ability, and it substitutes the argument to its `--devel-prefix` option for `%(prefix)s`. Is this useful or can it be removed as well? It seems like `aliBuild build` may have done this in the past as well, but not any more.
- The meanings of `-z`/`--devel-prefix` in `aliBuild build` and `aliBuild init` have apparently diverged significantly. See above -- is the option still needed for …
=> Improve command-line argument documentation

alibuild_helpers/analytics.py, alibuild_helpers/build.py, alibuild_helpers/cmd.py, alibuild_helpers/deps.py, alibuild_helpers/doctor.py, alibuild_helpers/git.py, alibuild_helpers/init.py, alibuild_helpers/log.py, alibuild_helpers/utilities.py, alibuild_helpers/workarea.py, tests/test_args.py, tests/test_build.py, tests/test_cmd.py, tests/test_utilities.py, tests/test_workarea.py
System checks shouldn't need to use the network, so disable it in Docker builds for a speed-up.
For regular builds, we can just use the host's network stack as we don't need any particular network features from Docker, and this way it's faster to set up and tear down containers.
This PR depends on #728, as it includes the commits from that PR. Once #728 is merged, I'll rebase and then this PR can be merged.
=> Use host network for Docker builds, and no network for system checks

alibuild_helpers/build.py, alibuild_helpers/cmd.py, tests/test_build.py
This happened on python3.6, as there, the system encoding (which for `LC_ALL=C` is ASCII) was used to decode command output. However, Vc has some branch names with UTF-8 non-breaking spaces in them. Reimplementing the function allows specifying an explicit encoding, which fixes this.
Tested on python3.6 using `LC_ALL=C`.
=> Fix encoding errors from getstatusoutput

alibuild_helpers/clean.py, tests/test_clean.py
As far as I can tell, this directory is only used for temporary storage between building and the proper installation directory, but it's not cleaned up when the build fails.
=> Cleanup INSTALLROOT

alibuild_helpers/sync.py, tests/test_sync.py
This should be a debug message instead, as it isn't a problem users need to be informed about a lot of the time.
=> Change confusing warning message when no tarball is found

alibuild_helpers/cmd.py
`subprocess.getstatusoutput` strips a single trailing newline, if one exists. Some calling code relies on this.
=> Make getstatusoutput behaviour match library function

alibuild_helpers/cmd.py
Add an encoding parameter, if supported, to match getstatusoutput and getoutput.
=> Fix encoding error in alibuild_helpers.cmd.execute

alibuild_helpers/build_template.sh
For "universal files", i.e. binaries with multiple architectures, otool displays all architectures' values, which confuses the script. Make it show only the arch we're building.
Tested and working on osx_arm64.
=> Fix otool invocation for multi-arch binaries

alibuild_helpers/sync.py, tests/test_build.py, tests/test_sync.py
This way, we only connect to a HTTP remote once, and then keep reusing this connection for each request. This should give a speed-up, especially for the many small requests when listing directories.
@ktf: Is it OK to keep a single connection open for the lifetime of the process, i.e. potentially hours? Or should aliBuild instead open a new connection for syncing each package individually, in which case we'd have to open 2n connections, where n is the number of packages needed, but each connection would only last a few seconds?
=> Use a connection pool for HTTP remote stores

alibuild_helpers/build.py
If a development package has committed or uncommitted changes, any packages depending on it should be rebuilt with the new code. This patch implements this.
This is done by incorporating the `devel_hash` of every dependency (if present) in a package's overall hash, so that if a dependency changes, we rebuild packages that depend on it. A dev package's hash itself doesn't change, however, so we keep rebuilding it in the same build area.
=> Rebuild later packages if dev package changes

alibuild_helpers/build.py
I must have missed this when extracting this code out into a function. So far it worked because everywhere `hash_data_for_key` is called, it can access `x` from the outer scope, but it should use its argument directly.
=> Fix variable name in storeHashes

alibuild_helpers/build.py
When a development package depends on another dev package, then when the latter changes, we should rebuild the former incrementally instead of fully.
Cc: @davidrohr
=> Rebuild dev packages incrementally when other dev package changes

alibuild_helpers/build.py, alibuild_helpers/build_template.sh, alibuild_helpers/cmd.py, alibuild_helpers/git.py, alibuild_helpers/init.py, alibuild_helpers/utilities.py, alibuild_helpers/workarea.py, tests/test_build.py, tests/test_init.py, tests/test_workarea.py
On CentOS 8, when we build our own OpenSSL from alidist, then subsequent git and curl calls fail, as they were compiled against the system OpenSSL, which has some special patches applied.
Therefore, install some wrapper scripts during the build that remove `LD_LIBRARY_PATH` and `DYLD_LIBRARY_PATH` from the environment temporarily for those programs.
When we call git from aliBuild itself (rather than from build scripts), also sanitise the environment. For this, I centralised (almost all) git calls to a single function.
This wrapping of calls needs to be done in two places, as we might be building inside a container, but we always run aliBuild's git commands on the host.
=> Use a wrapper script that sanitises the environment for OpenSSL-sensitive executables

aliBuild, alibuild_helpers/build.py, alibuild_helpers/templating_plugin.py, requirements.txt, setup.py
This allows access to the program state just before the build would start, exposed to a user-provided Jinja2 template.
Required for https://github.com/alisw/ali-bot/pull/1153.
=> Add a templating plugin

alibuild_helpers/workarea.py, tests/test_workarea.py
This got lost in the move to the `git()` function.
=> Re-add diagnostic output when cloning repos

alibuild_helpers/build_template.sh
Golang installs stuff without write permissions for the owning user sometimes. In this case, take write permissions explicitly, so we can delete the old build directory.
=> Explicitly take write permission before deleting

alibuild_helpers/build_template.sh
On MacOS, `xargs` gives up on substituting `{}` in a command if the substitution is too long.
=> Fix relocation of long paths on MacOS

alibuild_helpers/log.py
If stderr is line-buffered, ProgressPrint output will stutter severely or just not show up at all. Flush the stream after writing so output shows up immediately.
=> Fix ProgressPrint buffering

alibuild_helpers/build.py, alibuild_helpers/build_template.sh, alibuild_helpers/git.py, alibuild_helpers/init.py, alibuild_helpers/workarea.py, docs/troubleshooting.markdown, tests/test_build.py, tests/test_git.py, tests/test_init.py, tests/test_workarea.py
If a git repository cannot be accessed in parallel, try it sequentially while allowing the user to input their credentials. This fixes the issue where multiple git processes running in parallel would all present a username and password prompt, overwriting each other.
Avoiding password prompts entirely should be out of scope for aliBuild, as that requires changing the user's git configuration. Instead, I updated the documentation to specify how to cache passwords or use SSH auth instead.
Fixes #681
=> Allow users to input git credentials without prompts overwriting each other

alibuild_helpers/args.py, tests/testdist/defaults-o2.sh
With this patch, when users do not specify `--defaults` explicitly, `--defaults o2` is assumed. Previously, `--defaults release` was assumed.
=> Use o2 defaults by default, if no option is given

alibuild_helpers/args.py
These are for building stuff on ARM machines running slc7.
=> Teach aliBuild about slcX_aarch64 architectures

alibuild_helpers/cmd.py, tests/test_cmd.py
Running commands in Docker images with non-empty entrypoints fails. This fixes that issue.
Cc: @adriansev
=> Override Docker image entrypoint for DockerRunner too

alibuild_helpers/sync.py
This gets rid of "symlink couldn't be parsed" errors.
=> Normalise symlinks from HTTPS remotes

alibuild_helpers/cmd.py, alibuild_helpers/git.py
We want to avoid waiting for hours in CI if we can't update a git repository.
Add a `timeout=` argument to our `alibuild_helpers.cmd.*` functions and enforce it, at least where feasible, i.e. on Python 3.
=> Time out when git takes too long

alibuild_helpers/build.py
For development packages, we cannot see what's changed between runs, so always rebuild the package in that case, and rely on e.g. CMake to figure out if anything needs to be rebuilt.
No change in behaviour if there are no untracked files.
=> Always rebuild if there are untracked changes

.github/workflows/release.yml, .gitignore, alibuild_helpers/__init__.py, setup.py
The latest pip versions fail to install a source checkout if its version is set to `LAST_TAG`, which we do for all untagged commits.
Use setuptools_scm instead, so that we always have a valid, PEP440-compliant version number, even for commits in between tags.
=> Use setuptools_scm to single-source an always-valid version number

alibuild_helpers/build.py
If the user has a local directory named the same as an alidist package, that is interpreted as a development package (i.e. source code checkout) by aliBuild. However, if the package has no `source:` key in alidist, then this would not work. Instead of failing with a Python exception in that case, show a more helpful error message to the user.
=> Show helpful error message in case of name clashes

alibuild_helpers/cmd.py
Apparently, in some environments, running a simple interactive bash (`bash -i`) does not export `$PATH` automatically. In that case, the user must run a login shell (`bash -l`) instead.
Detect this where we rely on `$PATH` and show a more specific error message to the user.
=> Detect and fail early if `$PATH` is empty

aliBuild, alibuild_helpers/args.py, alibuild_helpers/build.py, alibuild_helpers/sync.py, alibuild_helpers/utilities.py, tests/test_args.py, tests/test_build.py, tests/test_cmd.py
Instead of using a function to prefix `ali` to everything, just hardcode the prefix.
On Guix, Python packages are installed with a wrapper script, and the aliBuild executable is called `.aliBuild-real`, which breaks this and `aliBuild init` tries to clone `https://github.com/alisw/.alidist`.
=> Remove `star()` function for experiment prefix

alibuild_helpers/build.py, alibuild_helpers/sync.py, tests/test_sync.py, tox.ini
If two aliBuild instances are building the same package at the same time and uploading it to S3, make sure that only one can upload at a time, and abort the other one.
There are probably ways to make aliBuild recover more intelligently from conflicts, but this commit only includes basic conflict detection.
=> Abort build when upload conflict on S3 is detected

alibuild_helpers/args.py
I've got a working `ubuntu2204-builder` container set up, and I've seeded S3 with initial builds up to O2. There's also a Jenkins job building nightlies on Ubuntu 22.04, just like on Ubuntu 20.04.
Overall, I'd say everything is in place for aliBuild to start automatically using precompiled tarballs on Ubuntu 22.04.
Unfortunately, this will change the behaviour of aliBuild slightly on Ubuntu 22.04: previously, system packages would be used if possible; after this change is applied, aliBuild defaults to `--no-system` instead, so that it can make best use of precompiled tarballs. To get back the previous behaviour, pass the `--no-remote-store` option to `aliBuild build`.
=> Automatically use S3 remote on Ubuntu 22.04

alienv
Due to reported problems using `alienv` in an Ubuntu container with some contamination from the CentOS 7 host environment, use `command -v` to find executable locations instead.
`command -v` is defined by POSIX and is a shell builtin in bash, so there should be no danger of environment contamination.
An alternative would be `type`, but its output is not in the correct format, and its exit code is not standardised by POSIX, so it may be unreliable as an existence check for a given executable.
@ktf: This should fix the problem reported via email last night.
=> Replace `which` with POSIX-compatible alternative

alibuild_helpers/build.py, tox.ini
Warn about uncommitted files in final summary
Too many times rebuilds have gone unnoticed because the per package
warning gets lost in the debug output. This tries to improve the issue
by adding a summary at the end with the list of directories containing
untracked files.
=> Warn about uncommitted files in final summary

alibuild_helpers/build.py, alibuild_helpers/git.py, alibuild_helpers/init.py, alibuild_helpers/scm.py, alibuild_helpers/workarea.py, tests/test_build.py, tests/test_hashing.py, tests/test_workarea.py
Abstract away SCM integration
The goal is to support different backends, like sapling.
=> Abstract away SCM integration

.github/workflows/pr-check.yml, alibuild_helpers/build.py, alibuild_helpers/sl.py, tests/test_build.py, tox.ini
Add support for sapling
Sapling is a somewhat novel SCM from Facebook / Meta.
It is fully compatible with Git and provides a more powerful
yet userfriendly frontend, modeled after mercurial.
This adds Sapling support in alibuild, including:
* Support for alidist sapling checkouts
* Support for development packages which were cloned via sapling
=> Add support for sapling

.github/workflows/pr-check.yml, alibuild_helpers/build.py, pyproject.toml, setup.py, tests/test_build.py, tests/test_workarea.py, tox.ini
Python 3.12 changes the default string representation of OrderedDicts, which aliBuild relies upon (this is obviously far from ideal, but we're stuck with it).
This patch hashes OrderedDicts in their old representation, to maintain hash compatibility between python<3.12 and python==3.12.
This saves e.g. Mac users from having to rebuild their entire sw directory when upgrading from python@3.11 to python@3.12 using brew.
Hashes are checked using unittests, so unittests passing should mean that hashes are computed exactly the same as before. (I found this issue by running the usual unittests on python3.12.) Take this opportunity to add a CI check under python3.12 to this repo.
=> Fix hashing on Python 3.12

alibuild_helpers/build.py
Fix invalid escape sequences by escaping the backslash properly.
This stops Python showing a bunch of warnings on every aliBuild invocation.
=> Fix SyntaxWarning on Python 3.12

alibuild_helpers/build.py, alibuild_helpers/build_template.sh, tests/test_build.py, tests/testdist/clobber-initdotsh.sh, tests/testdist/delete-etc.sh, tox.ini
This reduces the duplication in the init.sh generation code significantly.
Instead of generating shell commands that generate init.sh, scattered all over the place, generate the contents of init.sh in one place and just write them into the file when applicable.
Once created, load the generated file instead of generating the same shell code twice at different escaping levels.
All of this reduces the potential for errors a lot, since different places in the code don't need to be kept in sync when generating and re-generating the file.
Add tests that make sure the generated file contents are vaguely sensible, and that clobbering the file during the build (as the AliEn-Runtime package does) does not mean it is mangled during subsequent builds.
This PR requires #818 for the added tox test to …
=> Generate init.sh in one place

alibuild_helpers/build.py
If the last line in init.sh would load a package that was already loaded, [ -z ... ] returns false, which would mean the entire script's exit code is false, and the build would fail.
Fix this, so that the expression always returns true (either if the package is already loaded or if it is loaded by the line in question).
=> Fix crash when sourcing pre-build init.sh

alibuild_helpers/clean.py, tests/test_clean.py
1. Report the actual error when cleanup fails.
2. Keep going when one directory can't be deleted. This should stop one failing dir from completely blocking all cleanup in CI.
3. Use logging to show messages, to match the rest of aliBuild.
4. Fix decideClean docstring to match its code.
5. Adjust tests to match.
=> Improve error reporting in aliBuild clean

alibuild_helpers/build.py, tests/test_build.py
If users build e.g. O2Physics first with a branch called "x-y", and then later with a branch called "x", then aliBuild would print warnings about not being able to parse symlinks.
This is caused by an overly-broad glob when listing symlinks.
Replace this glob with a regex modelled after the regex that parses symlink targets, to avoid these false positives.
=> Avoid finding false-positive symlinks and printing warnings for them

alibuild_helpers/utilities.py, tests/test_packagelist.py
Previously, alibuild would always overwrite the `force_rebuild:` YAML key with the value of the `--force-rebuild` command-line flag, so the former would have no effect.
=> Fix force_rebuild setting when specified by recipe

aliBuild, alibuild_helpers/__init__.py, alibuild_helpers/args.py, alibuild_helpers/build.py, alibuild_helpers/build_template.sh, tests/test_args.py, tests/test_build.py
Write some more metadata for packages (augmenting and renaming the .full-dependencies file), including a user-supplied comment string, if any.
Users can supply comments using the new `--annotate PACKAGE=COMMENT` flag.
Currently, it is not checked whether the comment is actually applied. If the package is already installed, its comment is silently ignored.
=> Allow users to specify build comments

debian/control
Recommend the installation of pigz on Ubuntu as a dependency of alibuild. This means pigz will be installed by default, unless the user explicitly runs `apt install --no-install-recommends python3-alibuild`.
=> Install pigz by default on Ubuntu

alibuild_helpers/build_template.sh
This cuts the number of files considered for relocation in Python-modules down from 8k to 1k. This speeds up the Python-modules build significantly, since for each file, at least three processes are spawned.
=> Exclude more data files from MacOS relocation

docs/index.markdown
"pip" either uses Python 2, or it doesn't exist at all any more. Either way, we should encourage users to install our system packages (RPMs/DEBs/brew) instead, since they'll get automatic updates that way.
=> Fix outdated installation instructions

alibuild_helpers/git.py, alibuild_helpers/workarea.py, tests/test_build.py, tests/test_workarea.py
If git supports it, prefer the `--filter=tree:0` option to `--filter=blob:none`, but fall back to the latter if the former is not supported.
If using a Docker container, use neither (as before), since we don't know whether the git in the container can read the repo we produce outside the container.
=> Save more data in `sw/MIRROR` using `--filter=tree:0`

alibuild_helpers/build.py, alibuild_helpers/sync.py, alibuild_helpers/workarea.py, tests/test_build.py, tests/test_hashing.py, tests/test_sync.py, tests/test_workarea.py
See individual commits.
* Only download tarballs if we're going to use them (fixes https://its.cern.ch/jira/browse/O2-3882)
* Show download progress interactively (if possible) using `ProgressPrint`
* Show progress of cloning "mirror" repositories, replacing "spammy" per-repo output with one `ProgressPrint` (in non-debug mode)
Also contains one cleanup/refactoring commit (https://github.com/alisw/alibuild/commit/4236ab3044778141605f6e493ad275c46963daf5) -- let me know if you want a separate PR for that one.
=> UI improvements and tarballs fix

alibuild_helpers/build.py, alibuild_helpers/build_template.sh, alibuild_helpers/git.py, alibuild_helpers/init.py, alibuild_helpers/scm.py, alibuild_helpers/sl.py, alibuild_helpers/workarea.py, tests/test_build.py, tests/test_workarea.py
This lets us always use speed-up options like `--filter`, even when we're building inside a container.
We can also easily start using sapling for this in future by implementing the new SCM methods.
This also helps with some annoying authentication-related issues, if running inside `--docker`, such as in CI.
Fixes <https://its.cern.ch/jira/browse/O2-2439>.
When this is merged, we can also get rid of the `GIT_*` environment variables used in CI, and stop installing an especially-new Git version in our containers (since that was needed to understand the `GIT_*` variables).
This PR is based on https://github.com/alisw/alibuild/pull/834; once that is merged, I can rebase to get rid of the common commits.
=> Clone SOURCES repos outside container

alibuild_helpers/build_template.sh
If rsync is interrupted by the user while installing package files to their final path, it might already have copied the `.build-hash` file. That would cause `aliBuild` to assume that the package was fully installed on subsequent runs, even if some parts are missing.
Protect against this by explicitly creating the marker file last, after rsync has succeeded.
=> Protect package installation against interruption

alibuild_helpers/git.py, tests/test_build.py, tests/test_workarea.py
This change is not only performance related, it should also fix the missing blob object errors. Fetching with --filter=tree:0 should always be more resilient to missing objects upstream
```
sh-5.1$ git fetch -f https://github.com/alisw/alibuild-recipe-tools
+refs/tags/*:refs/tags/* +refs/heads/*:refs/heads/*
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 6 (delta 2), reused 6 (delta 2), pack-reused 0
Unpacking objects: 100% (6/6), 806 bytes | 806.00 KiB/s, done.
fatal: missing blob object '6f314120ba0359d1f73ad7d1d4a7f171fb36e8ac'
error: https://github.com/alisw/alibuild-recipe-tools did not send all necessary objects
```
=> Include clone_speedup_options in git fetch

alibuild_helpers/build.py, alibuild_helpers/build_template.sh, alibuild_helpers/sync.py
Support actual CVMFS stores
So far the cvmfs:// local store was actually supporting local installation
areas since installation layout in CVMFS is slightly different. We adapt to
support the proper CVMFS layout.
In the future we should probably have a separate mode for referring
to a non CVMFS layout.
=> Support actual CVMFS stores

alibuild_helpers/args.py, docs/docs/user.md
Finish the Ubuntu 24.04 integration. Closes [O2-5108](https://its.cern.ch/jira/browse/O2-5108)
Set as draft until the S3 artifacts are actually available
=> Fully support Ubuntu 24.04

aliBuild, alibuild_helpers/analytics.py, alibuild_helpers/build.py, alibuild_helpers/cmd.py, alibuild_helpers/git.py, alibuild_helpers/scm.py, alibuild_helpers/utilities.py, alibuild_helpers/workarea.py, setup.py, tests/test_args.py, tests/test_build.py, tests/test_clean.py, tests/test_cmd.py, tests/test_deps.py, tests/test_doctor.py, tests/test_hashing.py, tests/test_init.py, tests/test_log.py, tests/test_packagelist.py, tests/test_parseRecipe.py, tests/test_sync.py, tests/test_utilities.py, tests/test_workarea.py, tox.ini
Probably not ready to be merged, making PR to run the tests.
Also fixing some minor issues with the inheritance in ``class Git(SCM)``
=> Remove most Python 2 references

alibuild_helpers/build.py
Should make debugging logs easier
~~Still left to implement:~~
@ktf do you agree with the safe_args list? I think none should be leaking any secrets, but maybe docker_extra_args can?
Example output:
```
2024-11-18@13:55:57:ERROR:json-c:json-c:slc9_aarch64: Error while executing /alibuild/sw/SPECS/slc9_aarch64/json-c/v0.17.0-local1/build.sh on `alimachine'.
2024-11-18@13:55:57:ERROR:json-c:json-c:slc9_aarch64: Log can be found in /alibuild/sw/BUILD/json-c-latest/log
2024-11-18@13:55:57:ERROR:json-c:json-c:slc9_aarch64: Please upload it to CERNBox/Dropbox if you intend to request support.
2024-11-18@13:55:57:ERROR:json-c:json-c:slc9_aarch64: Build directory is /alibuild/sw/BUILD/json-c-latest/json-c.
2024-11-18@13:55:57:ERROR:json-c:json-c:slc9_aarch64: …
```
=> Dump some system info on error

alibuild_helpers/utilities.py, tests/test_packagelist.py
The current behaviour is to crash the build, but we can recover
gracefully by going back to building our own version instead.
Any trigger of this warning should be considered as a bug on the recipe,
though
=> Fall back to building the package if prefer_system_check fails

.github/workflows/pr-check.yml
Something changed in the default GitHub runners image again, and broke our setup
https://github.com/actions/runner-images/issues/10984
Error logs:
```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /opt/homebrew
Could not symlink bin/pkg-config
Target /opt/homebrew/bin/pkg-config
is a symlink belonging to pkg-config@0.29.2. You can unlink it:
brew unlink pkg-config@0.29.2
To force the link and overwrite all conflicting files:
brew link --overwrite pkgconf
To list all files that would be deleted:
brew link --overwrite pkgconf --dry-run
Possible conflicting files are:
/opt/homebrew/bin/pkg-config -> /opt/homebrew/Cellar/pkg-config@0.29.2/0.29.2_3/bin/pkg-config
/opt/homebrew/share/aclocal/pkg.m4 -> …
```
=> Fix macOS CI runner

tests/test_args.py, tox.ini
Use regular expressions to make sure we handle small differences in the error messages due to formatting of the arguments done by different versions of python.
=> Handle changes in argparse

tox.ini
=> Remove python2.7 test

pyproject.toml, requirements.txt, setup.py
This should allow us to bypass the removed cgi error (botocore removed
the dependency in 1.29.13)
=> Don't restrict boto3 as much

aliBuild
Fixes `Type "bool" is incompatible with type "() -> None"`
As discussed in
https://github.com/alisw/alibuild/pull/882/files#r1851624332
=> Don't redefine profiler variable to incompatible type

alibuild_helpers/utilities.py
Looks like a regression in #897
```bash
[root@56a05890a2a6 ~]# uvx aliBuild@1.17.14 build bogus
ERROR: [Errno 2] No such file or directory: 'alidist/bogus.sh'
[root@56a05890a2a6 ~]# uvx aliBuild@1.17.15 build bogus
Traceback (most recent call last):
File "/root/.cache/uv/archive-v0/GyJkpyQa9tPugmoKbsZ3N/bin/aliBuild", line 132, in <module>
doMain(args, parser)
File "/root/.cache/uv/archive-v0/GyJkpyQa9tPugmoKbsZ3N/bin/aliBuild", line 85, in doMain
doBuild(args, parser)
File "/root/.cache/uv/archive-v0/GyJkpyQa9tPugmoKbsZ3N/lib64/python3.9/site-packages/alibuild_helpers/build.py", line 490, in doBuild
getPackageList(packages                = packages,
File "/root/.cache/uv/archive-v0/GyJkpyQa9tPugmoKbsZ3N/lib64/python3.9/site-packages/alibuild_helpers/utilities.py", line 457, in …
```
=> Make sure recipe file exists before accessing it

alibuild_helpers/log.py
It confuses the typing check
As discussed beforehand, my goal is to eventually pass these strict mypy filter settings
I'll be tracking the progress in each PR, and try to fix the low hanging fruit first
```diff
-Found 788 errors in 33 files (checked 35 source files)
+Found 664 errors in 33 files (checked 35 source files)
```
The mypy filter
```ini
[mypy]
python_version = 3.12
platform = linux
plugins = pydantic.mypy
show_error_codes = true
follow_imports = normal
local_partial_types = true
strict_equality = true
no_implicit_optional = true
warn_incomplete_stub = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true
enable_error_code = ignore-without-code, redundant-self, truthy-iterable
disable_error_code = annotation-unchecked, import-not-found, …
```
=> Don't initialize the loggers to None

alibuild_helpers/utilities.py
In general when are remote store is provided, we disable system packages. However, this
should not be the case if the system package results in a new recipe, because in that case
we consider the result of that recipe to be the package.
=> Prefer system check which result in a new recipe should be treated as normal packages

.github/workflows/pr-check.yml, tox.ini
=> Drop 3.6 test

alibuild_helpers/build.py, alibuild_helpers/utilities.py, tests/testdist/tracking-env.sh, tox.ini
A recipe can now provide a dict in `track_env` where the
key is the name of an environment variable and the value
is a command which is executed to fill such environment variable.
This can be used to track system properties or environment variables
without having to resort to a system package.
=> Add support for tracking external environment

alibuild_helpers/build.py, alibuild_helpers/cmd.py, alibuild_helpers/doctor.py, tests/test_cmd.py, tests/test_packagelist.py
This way we don't leave traces in case the check happened to create
temporary files
CC @ktf @davidrohr
=> Run prefer_system_check in a temporary dir

alibuild_helpers/sync.py
By copying etc/profile.d/init.sh, rather than linking it, sourceing the
environment behaves like a local package even if in reality things come
from CVMFS via symlinks.
Kudos to @smuzaffar for the idea.
=> CVMFS support: make it look like we are running from the local build

.github/workflows/release.yml
We're no longer publishing the full tarball there but rather the .whl,
so we're migrating to the GitHub tarballs for the Homebrew script
Requires https://github.com/alisw/homebrew-system-deps/pull/41 merged first
=> Use Github tarballs rather than Pypi's

.github/workflows/release.yml
Reverts #943, I was wrong about the cause of the error. Pypi just
shuffled the URLs around for some reason
=> Use the right URL from pypi

alibuild_helpers/utilities.py, tests/test_utilities.py
Hi,
We've found that on Rocky9, the platform detection fails. This seems to be caused by the platform name containing a space, so I've adjusted the expected value to match:
```
>>> distro.linux_distribution()
('Rocky Linux', '9.6', 'Blue Onyx')
```
Regards,
Simon
=> Fix Rocky Linux detection

.github/workflows/pr-check.yml, tox.ini
Seems like a requirement from pypi. It can make the release fail to
publish, so it's better to check early
=> Add job to check readme before merge

.github/workflows/release.yml
Brew does this automatically from the URL
Requires https://github.com/alisw/homebrew-system-deps/pull/44 to be merged first
=> Homebrew publisher: Don't change the version of the package

alibuild_helpers/init.py
The performPreferCheck function in init.py was hardcoded to always return
(1, "") which caused all track_env commands to fail during initialization.
Fixes error: "Error while executing track_env for O2PhysicsO2PHYSICS_COMPONENTS: echo
${O2PHYSICS_COMPONENTS:-install} =>"
Regression spotted in alisw/alidist#5888
CC @ktf @fjonasALICE
Current output from master:
```
❯ aliBuild init O2Physics@master
WARNING: using existing recipes from ./alidist
ERROR: Error while executing track_env for O2PhysicsO2PHYSICS_COMPONENTS: echo ${O2PHYSICS_COMPONENTS:-install} =>
```
from this PR:
```
❮ ./aliBuild init O2Physics@master
WARNING: using existing recipes from ./alidist
==> Development directory . created for o2physics
```
=> Fix track_env command execution in aliBuild init
