alisw/alibuild

aliBuild

- Discover pigz if needed and use it.
- Make sure env property works.

Misc fixes to aliBuild

---

README.md
aliBuild
build_template.sh

Some minor edits too. It should be "retrocompatible" anyway but it's better to check.

External build script and improved README

---

aliBuild
build_template.sh

This set of commits is what I currently use to run the "gun" test and others in Jenkins.

Alibuild now able to build and run the "gun" test.

---

build_template.sh

We have now two generated scripts for relocating:
* `relocate-me.sh`: relocate according to `<arch>/<sw>/<ver>` structure, requires `$WORK_DIR` set in environment
* `relocate-me-root.sh`: relocates software root (assumed to be the dir where the script is) into either the current directory, or `$NEW_PREFIX` (if set)
The latter is fully compatible with any legacy behaviour (*i.e.* relocating on current CVMFS structure).

Additional script relocates from software root dir

---

README.md
aliBuild
build_template.sh

This allows people to develop the packages being built without having to pass by a given commit - push -pull cycle.

Add development mode

---

README.md
aliBuild
build_template.sh

Main new features:
- Support for in Docker builds.
- Support for runtime only repository structure.

New version of aliBuild

---

aliBuild

@fuhlig1 @dberzano here is what we discussed.

Add the ability to disable packages

---

yaml/README
yaml/__init__.py
yaml/composer.py
yaml/constructor.py
yaml/cyaml.py
yaml/dumper.py
yaml/emitter.py
yaml/error.py
yaml/events.py
yaml/loader.py
yaml/nodes.py
yaml/parser.py
yaml/reader.py
yaml/representer.py
yaml/resolver.py
yaml/scanner.py
yaml/serializer.py
yaml/tokens.py

Looks like many distributions actually lack it, so we include our own
copy to avoid issues.

Add PyYAML 3.09 to simplify deployment

---

reference.markdown
user.markdown

Do not merge until the feature is actually merged into master.

Documentation for "prefer system" options

---

_config.yml
index.markdown
quick.markdown
side-menu.css
troubleshooting.markdown
user.markdown

- Instant gratification pages now specify how to read the rest of the
documentation.
- Streamlined quickstart docs moving --architecture to the user guide.
- SUPPORT renamed to TROUBLESHOOTING with CSS adapted.

Improved documentation.

---

.travis.yml

This checks pull requests to alibuild by building zlib. Notice this will
simply pick up the system one, so it really acts as sanity check more
than anything.

Add Travis-CI checks

---

aliBuild

- `--disable foo --disable bar` now behaves as `--disable foo,bar`. Fixes #139.

Handle gracefully multiple --disable options

---

aliBuild

Also print out the default if `--defaults` is specified without an
option.

List available defaults when a wrong one is specified

---

build_template.sh

This should fix issues with modulefiles for development packages.

Always relocate modulefiles

---

aliBuild

Unpretty hardcoding sometimes is better than broken generic solution.

Correctly handle main packages.

---

aliBuild

Defaults to the name of the current directory.

Allow to specify own version for devel packages

---

aliBuild

This is actually a bug that needs to be fixed quickly :-(

Fix for when log message is not a string

---

Jenkinsfile

Add Jenkinsfile for alibuild

---

aliBuild

When invoked it will clean remove all the packages which are not
part of one of the "latest" builds.

Add clean sub-command

---

alienv

User is warned with an error message.
Fixes #173.

alienv fails when loading missing Modulefiles

---

alibuild_helpers/build_template.sh

No incremental build if the first one failed

---

aliBuild

`aliBuild version` prints out aliBuild version.

Add version action

---

codecov.yml

Strip the project folder to fix relative paths

---

alienv

Silence harmless missing Toolchain error in alienv

---

tutorial.markdown

Take into account Michele's feedback.

Improve tutorial

---

alibuild_helpers/utilities.py

This will make sure a proper error message is shown.

Fix issue when non existing package is specified

---

docs/o2-tutorial.markdown

As requested by @ktf, here is the little tutorial I made for O2 modules.

Add tutorial for O2Group modules

---

aliBuild
alibuild_helpers/build_template.sh

Add option to make tar work on NFS

---

docs/o2-tutorial.markdown

- alibuild version
- real-world package instead of "ABC"

Fix o2 tutorial

---

alibuild_helpers/build.py

Remove special cases for setting mainPackage

---

docs/o2-daq-tutorial.markdown

I saw a user fail to use this last part of the instructions. Thus I tried to simplify and clarify it.

Make clearer instructions for usage

---

docs/SUPPORT

See https://github.com/blog/2400-support-file-support

Add SUPPORT file

---

alienv

Add alienv warning when SIP is enabled

---

.travis.yml
docs/o2-tutorial.markdown
docs/reference.markdown
docs/tutorial.markdown
docs/user.markdown
script/cibuild

- Add a standalone script
- Attempt to build website pages while running tests

Improve tests

---

alienv

* New modules repository: https://github.com/cea-hpc/modules
* See also https://modules.readthedocs.io/en/latest/MIGRATING.html

Fix for alienv with modules >= 4.0 plus minor improvements

---

alibuild_helpers/build.py

Encourage users to upload logs to CERNBox/DropBox

---

alienv

After more than 10 years without any release, environment-modules keeps being updated quite frequently with either critical bugs or new features breaking a user space which was just fine.

Fix environment-modules problems on macOS

---

alibuild_helpers/build_template.sh

Still does not work with alienv yet.

Make build passing with SIP

---

.pylintrc
.travis.yml
script/cibuild

Current configuration is the minimal one to have everything green
we should little by little make sure we enable the tests as it
makes sense and as we find the time to actually fix them.

Add pylint to Travis tests

---

alibuild_helpers/log.py
script/cibuild
tests/test_log.py

Tests are included. Format example: `[1234/5678]`

Add detection of Ninja-style progress

---

alibuild_helpers/build_template.sh

This allows nested direnv specified environments.

Add source_up to init.sh

---

docs/quick.markdown

This should fix the travis PR checker.

Add missing anchor in documentation

---

alibuild_helpers/build.py

* Silence python warnings
* Add sha256 sum for each tarball
* Add redirection for each tarball

More fixes for S3 repository

---

aliBuild

This should improve ability to debug errors people are having
sporadically  when on AFS.

Improve error message when unable to change dir

---

alienv

Not needed anymore and broken by recent homebrew upgrade.

Do not use MODULES_USE_COMPAT_VERSION=1

---

alibuild_helpers/args.py
alibuild_helpers/build.py
tests/test_args.py

Time to say goodbye to alicache.

Switch to S3 as default slc7 remote

---

alibuild_helpers/build.py

This seems to cut 4 / 5 seconds from an empty build, bringing it
from 17 seconds to 12 in the O2 case, at least on my machine.

Optimize symlink creation

---

alibuild_helpers/build.py

These are lots of small files, so debug output from `getRetry` tends to overwhelm the logs. This patch disables debug output for symlink downloads, unless they fail.

Don't show debug output by default for symlink downloads

---

alibuild_helpers/build.py
alibuild_helpers/log.py
tests/test_log.py

This should catch the last places where various things are used like loggers, but don't support formatting.

Fix logging errors

---

alibuild_helpers/sync.py

With this commit, aliBuild looks for a `<package>.manifest` file listing symlink names and targets, in order to avoid having to download many small files.
The manifest file is a simple text file, so symlink names and targets must not contain newlines, and symlink names must not contain tab characters.
This change is backwards-compatible: the many individual pseudo-symlinks can stay; they will be simply ignored (and not downloaded) if they appear in the manifest. Old aliBuild versions will ignore the manifest and can continue to use the individual pseudo-symlink files.
Needs testing.

Use a manifest file to speed up symlink downloads

---

alibuild_helpers/args.py
alibuild_helpers/build.py
alibuild_helpers/doctor.py
alibuild_helpers/utilities.py
tests/test_utilities.py

Fixes to Docker support for use in CI

---

alibuild_helpers/build.py
alibuild_helpers/sync.py

Instead of duplicating sync logic, put the code that uploads links in `TARS/$arch/dist/` into the sync helpers as well.
This will make it easier to add more sync helpers later, such as the boto3 one.
Tested and working locally using the `s3://` remote.

Move all sync code into alibuild_helpers.sync

---

.github/workflows/release.yml

I haven't tested this as a whole.

Auto-publish releases to Homebrew

---

docs/reference.markdown

Remove variable that is not provided; fix spelling for another one.

Fix build variable documentation

---

docs/index.markdown
docs/quick.markdown
docs/reference.markdown
docs/troubleshooting.markdown
docs/user.markdown

Make http:// links https://, and fix a link to the PIP docs that has moved.

Fix documentation linting

---

alibuild_helpers/build.py

This makes `ProgressPrint` available when building using Docker (but with stdout being a terminal, so interactive use only).

Print progress for interactive Docker builds too

---

alienv

Signed-off-by: Martin Vala <mvala@saske.sk>

Added --dev support

---

alibuild_helpers/utilities.py

https://github.com/alisw/alibuild/pull/808

[O2-4323] Fix RHEL9 support in aliBuild CLI

---

alibuild_helpers/deps.py

Prettier deps plots by default

Prettier deps plots by default

---

alibuild_helpers/build_template.sh

In particular, the AliEn-Runtime build overwrites init.sh. That makes subsequent builds fail, so regenerate init.sh after each build. (Re-)writing init.sh after the build matches the previous behaviour of alibuild.

Regenerate init.sh after each build, in case it was clobbered

---

alibuild_helpers/utilities.py
tests/test_build.py

To match hashes of the "defaults-release" package to previous alibuild versions, the recipe needs to be blank.
Warn the user if any ignored recipe is found. Recipes consisting only of comment lines don't trigger this warning.

Ignore recipe in defaults-*.sh to match old behaviour

---

alibuild_helpers/args.py

This makes aliDoctor have the same defaults for `--no-system` as aliBuild, specifically on platforms like `slc7_x86-64`, where we use the remote by default (implying `--no-system` by default).
Copy all remote-related arguments to the aliDoctor options for consistency. This would also allow aliDoctor to query the remote directly in future, and e.g. list packages that will be downloaded separately from packages that will actually be compiled locally.
Fixes <https://github.com/alisw/alibuild/issues/643>.

Make aliDoctor's and aliBuild's treatment of remotes consistent

---

alibuild_helpers/doctor.py

Check for valid c++ compiler in docker, if needed
---
[//]: # (BEGIN SAPLING FOOTER)
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/alisw/alibuild/pull/839).
* #838
* #840
* __->__ #839

Check for valid c++ compiler in docker, if needed

---

alibuild_helpers/doctor.py

Migrate to Alma9 the message regarding prerequisites
---
[//]: # (BEGIN SAPLING FOOTER)
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/alisw/alibuild/pull/840).
* #838
* __->__ #840
* #839

Migrate to Alma9 the message regarding prerequisites

---

.github/workflows/pr-check.yml
.github/workflows/release.yml

Support Node 20 as required by Github

Support Node 20 as required by Github

---

alibuild_helpers/build.py

Correctly propagate build deps of runtime deps

Correctly propagate build deps of runtime deps

---

aliBuild
aliDeps
aliDoctor
alibuild_helpers/analytics.py
alibuild_helpers/deps.py
alibuild_helpers/doctor.py
alibuild_helpers/utilities.py
pb
setup.py

Drop support for python2

---

alibuild_helpers/git.py

Consider all git repositories managed by aliBuild as safe.

Consider all git repositories managed by aliBuild as safe.

---

alibuild_helpers/git.py

Do not override externally set GIT_CONFIG_COUNT

Do not override externally set GIT_CONFIG_COUNT

---

docs/docs/stylesheets/extra.css

The change in 54bf67e was affecting the link colours too

Fix link colours in documentation

---

.github/workflows/documentation.yml
docs/docs/o2-tutorial.md
docs/docs/tutorial.md
docs/mkdocs.yml

Fix broken redirect

---

alibuild_helpers/args.py

Support downloading packages for ARM

Support downloading packages for ARM

---

alibuild_helpers/sync.py

Support CVMFS based remote store
This introduces experimental support for reusing packages which
were built with aliBuild and were deployed on CVMFS (or similar shared
filesystem).
It works by locating the package with the correct hash, and creating a
tarball with a symlink to it. For this reasons, this cannot be used
to upload tarballs.

Support CVMFS based remote store

---

setup.py

We accidentally changed the wrong list in #862

Fix error in setup.py

---

alibuild_helpers/build.py

Should make it easier to debug user logs

List packages currently in development mode before building

---

aliBuild

- Unused import
- Duplicate key in dictionary

Fix minor issues

---

alibuild_helpers/sync.py

I think this should always crash

Fix typo on CVMFS upload function

---

docs/docs/reference.md
tests/test_build.py

Current recipe source changed recently

Fix tests involving zlib repo

---

.github/workflows/pr-check.yml
tox.ini

Disable PEP8 test

---

.github/workflows/pr-check.yml

Bump ubuntu builder

---

aliBuild
alibuild_helpers/deps.py
tests/test_args.py
tests/test_build.py
tests/test_clean.py
tests/test_cmd.py
tests/test_doctor.py
tests/test_packagelist.py

Delete __future__ annotation

---

alibuild_helpers/cmd.py

Fix multiline env variables

---

tests/test_cmd.py

Add tests for multiline env variables

---

alibuild_helpers/build.py

---
[//]: # (BEGIN SAPLING FOOTER)
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/alisw/alibuild/pull/969).
* #970
* #967
* __->__ #969

Handle the case sapling is in git mode
